### ISSUE TITLE
membuat manual book admin

### ISSUE THREAD

**Issue by ricardsimon** [lintangtimur/ManajemenProyek#50]

**Comment by danieladitama11** [comment]
[User Manual Admin.docx](https://github.com/lintangtimur/ManajemenProyek/files/2614418/User.Manual.Admin.docx)
Sudah mon terlampir filenya

**Comment by ricardsimon** [comment]
masih kosong daftar isi, perbaiki daftar isi

**Comment by danieladitama11** [comment]
[User.Manual.Admin2.docx](https://github.com/lintangtimur/ManajemenProyek/files/2614437/User.Manual.Admin2.docx)
Sudah diupdate @ricardsimon
